[project]
name = 'Multidimensional-Art-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.curation-process]
path = 'contracts/curation-process.clar'
clarity_version = 2
epoch = 2.5

[contracts.inter-dimensional-exhibition]
path = 'contracts/inter-dimensional-exhibition.clar'
clarity_version = 2
epoch = 2.5

[contracts.multidimensional-artwork]
path = 'contracts/multidimensional-artwork.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
